export const projectConstants = {
    FETCH_PROJECTS_REQUEST: 'FETCH_PROJECTS_REQUEST',
    FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
    FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_FAILURE',
}

export const actionConstants = {
    FETCH_ACTIONS_REQUEST: 'FETCH_ACTIONS_REQUEST',
    FETCH_ACTIONS_SUCCESS: 'FETCH_ACTIONS_SUCCESS',
    FETCH_ACTIONS_FAILURE: 'FETCH_ACTIONS_FAILURE',
}